import { SessionRun, ApprovalItem } from "../types/telemetry";

export const getMockSessions = (): SessionRun[] => {
  const now = Date.now();
  const timeOffset = (minsAgo: number) => new Date(now - minsAgo * 60 * 1000).toISOString();

  const retryFailureSession: SessionRun = {
    id: "run-retry-fail-501",
    runId: "run-retry-fail-501",
    agentName: "ProspectAI Lead Enricher",
    status: "RECOVERED",
    startTime: timeOffset(25),
    endTime: timeOffset(24),
    durationMs: 3400,
    totalCostUsd: 0.00042,
    totalTokens: 1250,
    promptTokens: 1000,
    completionTokens: 250,
    model: "gpt-4o",
    eventsCount: 3,
    toolsUsedCount: 1,
    piiFilteredCount: 1,
    loopAlertTriggered: false,
    clientSecurityAlertsCount: 0,
    clientDataRenderedCount: 1,
    attempts: 1,
    maxRetries: 3,
    retriedErrors: ["RateLimitError: 429 Too Many Requests on CRM webhook"],
    replayedBy: "run-retry-success-502",
    metadata: {
      replayedBy: "run-retry-success-502",
      errorType: "RateLimitError",
    },
    events: [
      {
        type: "STEP_START",
        stepName: "fetch-crm-lead",
        timestamp: timeOffset(25),
      },
      {
        type: "TOOL_EXECUTION",
        toolId: "crm_01",
        toolName: "fetchLead",
        aliasUsed: "crm_fetch",
        depth: 1,
        durationMs: 350,
        success: true,
        llmSummary: { leadId: "lead_884", name: "Marc Dupont", company: "Nexus SAS" },
        rawPayload: { email: "m.dupont@nexus.fr", phone: "+33600000000" },
        piiFilteredCount: 1,
        costUsd: 0.00005,
        cached: false,
        timestamp: timeOffset(24.8),
      },
      {
        type: "STEP_FAILED",
        stepName: "sync-webhook",
        error: "RateLimitError: 429 Too Many Requests on CRM webhook",
        durationMs: 2900,
        timestamp: timeOffset(24.2),
      },
    ],
  };

  const retrySuccessSession: SessionRun = {
    id: "run-retry-success-502",
    runId: "run-retry-success-502",
    agentName: "ProspectAI Lead Enricher",
    status: "COMPLETED",
    startTime: timeOffset(20),
    endTime: timeOffset(19),
    durationMs: 2800,
    totalCostUsd: 0.00055,
    totalTokens: 1450,
    promptTokens: 1100,
    completionTokens: 350,
    model: "gpt-4o",
    eventsCount: 4,
    toolsUsedCount: 2,
    piiFilteredCount: 1,
    loopAlertTriggered: false,
    clientSecurityAlertsCount: 0,
    clientDataRenderedCount: 2,
    attempts: 2,
    maxRetries: 3,
    retryOf: "run-retry-fail-501",
    metadata: {
      retryOf: "run-retry-fail-501",
      attempts: 2,
      strategy: "exponential_backoff",
    },
    events: [
      {
        type: "STEP_START",
        stepName: "fetch-crm-lead",
        timestamp: timeOffset(20),
      },
      {
        type: "TOOL_EXECUTION",
        toolId: "crm_01",
        toolName: "fetchLead",
        aliasUsed: "crm_fetch",
        depth: 1,
        durationMs: 120,
        success: true,
        llmSummary: { leadId: "lead_884", name: "Marc Dupont", company: "Nexus SAS" },
        rawPayload: { email: "m.dupont@nexus.fr", phone: "+33600000000" },
        piiFilteredCount: 1,
        costUsd: 0.00002,
        cached: true,
        timestamp: timeOffset(19.8),
      },
      {
        type: "TOOL_EXECUTION",
        toolId: "webhook_02",
        toolName: "pushWebhook",
        aliasUsed: "crm_webhook",
        depth: 1,
        durationMs: 450,
        success: true,
        llmSummary: { delivered: true, statusCode: 200 },
        piiFilteredCount: 0,
        costUsd: 0.00008,
        cached: false,
        timestamp: timeOffset(19.4),
      },
      {
        type: "STEP_COMPLETED",
        stepName: "sync-webhook",
        durationMs: 500,
        piiDetectedCount: 0,
        resultSummary: { success: true, verifiedStatus: 200 },
        timestamp: timeOffset(19.2),
      },
    ],
  };

  const retryingParentSession: SessionRun = {
    id: "run-retrying-live-601",
    runId: "run-retrying-live-601",
    agentName: "BillingAssistant",
    status: "RETRYING",
    startTime: timeOffset(8),
    durationMs: 1200,
    totalCostUsd: 0.0003,
    totalTokens: 900,
    promptTokens: 750,
    completionTokens: 150,
    model: "claude-3-5-sonnet-20241022",
    eventsCount: 2,
    toolsUsedCount: 1,
    piiFilteredCount: 0,
    loopAlertTriggered: false,
    clientSecurityAlertsCount: 0,
    clientDataRenderedCount: 0,
    attempts: 1,
    maxRetries: 3,
    replayedBy: "run-retrying-active-602",
    metadata: {
      replayedBy: "run-retrying-active-602",
    },
    events: [
      {
        type: "STEP_START",
        stepName: "verify-subscription",
        timestamp: timeOffset(8),
      },
      {
        type: "STEP_FAILED",
        stepName: "verify-subscription",
        error: "GatewayTimeout: 504 Stripe billing endpoint timed out",
        timestamp: timeOffset(7.8),
      },
    ],
  };

  const retryingActiveSession: SessionRun = {
    id: "run-retrying-active-602",
    runId: "run-retrying-active-602",
    agentName: "BillingAssistant",
    status: "RUNNING",
    startTime: timeOffset(2),
    durationMs: 2000,
    totalCostUsd: 0.00032,
    totalTokens: 950,
    promptTokens: 800,
    completionTokens: 150,
    model: "claude-3-5-sonnet-20241022",
    eventsCount: 1,
    toolsUsedCount: 1,
    piiFilteredCount: 0,
    loopAlertTriggered: false,
    clientSecurityAlertsCount: 0,
    clientDataRenderedCount: 0,
    attempts: 2,
    maxRetries: 3,
    retryOf: "run-retrying-live-601",
    metadata: {
      retryOf: "run-retrying-live-601",
      attempts: 2,
    },
    events: [
      {
        type: "STEP_START",
        stepName: "verify-subscription-retry",
        timestamp: timeOffset(2),
      },
    ],
  };

  const prospectQualifierSession: SessionRun = {
    id: "run-prospect-101",
    runId: "run-prospect-101",
    agentName: "prospect-qualifier",
    status: "WAITING_APPROVAL",
    startTime: timeOffset(45),
    durationMs: 1420,
    totalCostUsd: 0.000459,
    totalTokens: 1750,
    promptTokens: 1350,
    completionTokens: 400,
    model: "gpt-4o-mini",
    eventsCount: 4,
    toolsUsedCount: 1,
    piiFilteredCount: 3,
    loopAlertTriggered: false,
    clientSecurityAlertsCount: 0,
    clientDataRenderedCount: 1,
    userFeedback: {
      rating: "POSITIVE",
      tag: "HELPFUL",
      comment: "Directeurs pertinents identifiés sans exposer d'emails confidentiels.",
    },
    events: [
      {
        type: "STEP_START",
        stepName: "fetch-prospect-data",
        timestamp: timeOffset(45),
      },
      {
        type: "TOOL_EXECUTION",
        toolId: "crm_lookup_01",
        toolName: "searchCRM",
        aliasUsed: "lookup_crm",
        depth: 1,
        durationMs: 340,
        success: true,
        llmSummary: { found: true, leadScore: 85, company: "Acme Corp" },
        rawPayload: { email: "ceo@acme.com", phone: "+33612345678", revenue: "$10M" },
        piiFilteredCount: 3,
        tokens: { promptTokens: 120, completionTokens: 60, totalTokens: 180 },
        costUsd: 0.00008,
        cached: false,
        timestamp: timeOffset(44.6),
      },
      {
        type: "CLIENT_DATA_RENDERED",
        toolId: "crm_lookup_01",
        channel: "HTTP",
        renderedItemCount: 1,
        timestamp: timeOffset(44.4),
      },
      {
        type: "STEP_COMPLETED",
        stepName: "fetch-prospect-data",
        durationMs: 420,
        piiDetectedCount: 3,
        resultSummary: { success: true },
        timestamp: timeOffset(44.2),
      },
      {
        type: "STEP_APPROVAL_REQUEST",
        stepName: "send-outreach-email",
        actionType: "SEND_OUTREACH_EMAIL",
        payloadSummary: {
          recipientDomain: "acme.com",
          template: "executive_pitch",
          leadScore: 85,
          channel: "Email",
        },
        timestamp: timeOffset(44.0),
      },
      {
        type: "USER_FEEDBACK",
        rating: "POSITIVE",
        feedbackTag: "HELPFUL",
        userComment: "Directeurs pertinents identifiés sans exposer d'emails confidentiels.",
        timestamp: timeOffset(43.5),
      },
    ],
  };

  const leadEnricherSession: SessionRun = {
    id: "run-enrich-202",
    runId: "run-enrich-202",
    agentName: "lead-enricher",
    status: "COMPLETED",
    startTime: timeOffset(75),
    endTime: timeOffset(74.5),
    durationMs: 3200,
    totalCostUsd: 0.00185,
    totalTokens: 4600,
    promptTokens: 3800,
    completionTokens: 800,
    model: "claude-3-5-sonnet-20241022",
    eventsCount: 4,
    toolsUsedCount: 2,
    piiFilteredCount: 5,
    loopAlertTriggered: false,
    clientSecurityAlertsCount: 0,
    clientDataRenderedCount: 2,
    events: [
      {
        type: "STEP_START",
        stepName: "enrich-linkedin-profile",
        timestamp: timeOffset(75),
      },
      {
        type: "TOOL_EXECUTION",
        toolId: "linkedin_01",
        toolName: "scrapeCompanyData",
        aliasUsed: "fetch_company",
        depth: 1,
        durationMs: 890,
        success: true,
        llmSummary: { employeesCount: 250, industry: "Fintech", hq: "Paris" },
        rawPayload: { executiveName: "Alice Martin", directPhone: "+33140506070" },
        piiFilteredCount: 2,
        tokens: { promptTokens: 350, completionTokens: 120, totalTokens: 470 },
        costUsd: 0.00045,
        cached: false,
        timestamp: timeOffset(74.8),
      },
      {
        type: "CLIENT_DATA_RENDERED",
        toolId: "linkedin_01",
        channel: "HTTP",
        renderedItemCount: 2,
        timestamp: timeOffset(74.7),
      },
      {
        type: "STEP_COMPLETED",
        stepName: "enrich-linkedin-profile",
        durationMs: 950,
        piiDetectedCount: 2,
        resultSummary: { verified: true },
        timestamp: timeOffset(74.6),
      },
    ],
  };

  const threatBlockedSession: SessionRun = {
    id: "run-threat-404",
    runId: "run-threat-404",
    agentName: "prospect-qualifier",
    status: "FAILED",
    startTime: timeOffset(90),
    endTime: timeOffset(89.9),
    durationMs: 200,
    totalCostUsd: 0,
    totalTokens: 0,
    promptTokens: 0,
    completionTokens: 0,
    model: "gpt-4o-mini",
    eventsCount: 1,
    toolsUsedCount: 0,
    piiFilteredCount: 1,
    loopAlertTriggered: false,
    clientSecurityAlertsCount: 1,
    clientDataRenderedCount: 0,
    events: [
      {
        type: "CLIENT_SECURITY_ALERT",
        alertType: "SUSPECTED_SECRET_INPUT",
        inputLength: 48,
        matchedPatternSnippet: "sk-ant-api03-ab9...",
        timestamp: timeOffset(90),
      },
    ],
  };

  return [
    retrySuccessSession,
    retryFailureSession,
    retryingActiveSession,
    retryingParentSession,
    prospectQualifierSession,
    leadEnricherSession,
    threatBlockedSession,
  ];
};

export const getMockApprovals = (): ApprovalItem[] => {
  const now = Date.now();
  const timeOffset = (minsAgo: number) => new Date(now - minsAgo * 60 * 1000).toISOString();

  return [
    {
      id: "appr_01",
      runId: "run-prospect-101",
      agentName: "prospect-qualifier",
      stepName: "send-outreach-email",
      actionType: "SEND_OUTREACH_EMAIL",
      payloadSummary: {
        recipientDomain: "acme.com",
        template: "executive_pitch",
        leadScore: 85,
        estimatedDealSize: "$50,000",
      },
      status: "PENDING",
      createdAt: timeOffset(44),
    },
    {
      id: "appr_ttl_expired",
      runId: "run-threat-404",
      agentName: "prospect-qualifier",
      stepName: "execute-wire-transfer",
      actionType: "EXECUTE_WIRE_TRANSFER",
      payloadSummary: {
        amountUsd: 75000,
        beneficiary: "Supplier Corp",
        iban: "FR76****************12",
      },
      status: "REJECTED",
      createdAt: new Date(now - 28 * 3600 * 1000).toISOString(),
      decidedAt: new Date(now - 4 * 3600 * 1000).toISOString(),
      decidedBy: "System (TTL)",
      reason: "Auto-expired: SLA timeout exceeded (24h)",
    },
  ];
};
